const BET_COMPONENTS = [
  { name: 'amount', type: 'uint256' },
  { name: 'oddsAmount', type: 'uint256' },
  { name: 'point', type: 'uint8' },
] as const;

const PLACE_COMPONENTS = [
  { name: 'amount', type: 'uint256' },
  { name: 'working', type: 'bool' },
] as const;

const HARDWAY_COMPONENTS = [{ name: 'amount', type: 'uint256' }] as const;

const ONE_ROLL_COMPONENTS = [
  { name: 'field', type: 'uint256' },
  { name: 'any7', type: 'uint256' },
  { name: 'anyCraps', type: 'uint256' },
  { name: 'craps2', type: 'uint256' },
  { name: 'craps3', type: 'uint256' },
  { name: 'yo', type: 'uint256' },
  { name: 'twelve', type: 'uint256' },
  { name: 'horn', type: 'uint256' },
] as const;

export const crapsGameV2Abi = [
  {
    type: 'function',
    name: 'getPlayerState',
    stateMutability: 'view',
    inputs: [{ name: 'player', type: 'address' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'phase', type: 'uint8' },
          { name: 'puckState', type: 'uint8' },
          { name: 'point', type: 'uint8' },
          { name: 'lastActivityTime', type: 'uint48' },
          { name: 'pendingRequestId', type: 'uint256' },
          { name: 'available', type: 'uint256' },
          { name: 'inPlay', type: 'uint256' },
          { name: 'reserved', type: 'uint256' },
          { name: 'bankroll', type: 'uint256' },
          { name: 'totalBankroll', type: 'uint256' },
          { name: 'initialBankroll', type: 'uint256' },
          { name: 'accruedFees', type: 'uint256' },
          { name: 'paused', type: 'bool' },
          { name: 'selfExcluded', type: 'bool' },
          { name: 'operatorExcluded', type: 'bool' },
          { name: 'reinstatementEligibleAt', type: 'uint256' },
          {
            name: 'bets',
            type: 'tuple',
            components: [
              { name: 'passLine', type: 'tuple', components: BET_COMPONENTS },
              { name: 'dontPass', type: 'tuple', components: BET_COMPONENTS },
              { name: 'come', type: 'tuple[4]', components: BET_COMPONENTS },
              { name: 'dontCome', type: 'tuple[4]', components: BET_COMPONENTS },
              { name: 'place4', type: 'tuple', components: PLACE_COMPONENTS },
              { name: 'place5', type: 'tuple', components: PLACE_COMPONENTS },
              { name: 'place6', type: 'tuple', components: PLACE_COMPONENTS },
              { name: 'place8', type: 'tuple', components: PLACE_COMPONENTS },
              { name: 'place9', type: 'tuple', components: PLACE_COMPONENTS },
              { name: 'place10', type: 'tuple', components: PLACE_COMPONENTS },
              { name: 'lay4', type: 'tuple', components: PLACE_COMPONENTS },
              { name: 'lay5', type: 'tuple', components: PLACE_COMPONENTS },
              { name: 'lay6', type: 'tuple', components: PLACE_COMPONENTS },
              { name: 'lay8', type: 'tuple', components: PLACE_COMPONENTS },
              { name: 'lay9', type: 'tuple', components: PLACE_COMPONENTS },
              { name: 'lay10', type: 'tuple', components: PLACE_COMPONENTS },
              { name: 'hard4', type: 'tuple', components: HARDWAY_COMPONENTS },
              { name: 'hard6', type: 'tuple', components: HARDWAY_COMPONENTS },
              { name: 'hard8', type: 'tuple', components: HARDWAY_COMPONENTS },
              { name: 'hard10', type: 'tuple', components: HARDWAY_COMPONENTS },
              { name: 'oneRolls', type: 'tuple', components: ONE_ROLL_COMPONENTS },
            ],
          },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'openSession',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'closeSession',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'deposit',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'withdraw',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'placeBet',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'betType', type: 'uint8' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'placeIndexedBet',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'betType', type: 'uint8' },
      { name: 'index', type: 'uint8' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'removeBet',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'betType', type: 'uint8' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'removeIndexedBet',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'betType', type: 'uint8' },
      { name: 'index', type: 'uint8' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setPlaceWorking',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'placeNumber', type: 'uint8' },
      { name: 'working', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setLayWorking',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'layNumber', type: 'uint8' },
      { name: 'working', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'executeTurn',
    stateMutability: 'nonpayable',
    inputs: [
      {
        name: 'actions',
        type: 'tuple[]',
        components: [
          { name: 'kind', type: 'uint8' },
          { name: 'betType', type: 'uint8' },
          { name: 'index', type: 'uint8' },
          { name: 'amount', type: 'uint256' },
          { name: 'working', type: 'bool' },
        ],
      },
      { name: 'rollAfter', type: 'bool' },
    ],
    outputs: [{ name: 'requestId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'rollDice',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [{ name: 'requestId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'selfExclude',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'requestSelfReinstatement',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'completeSelfReinstatement',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  { type: 'function', name: 'token', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address' }] },
  {
    type: 'event',
    name: 'SessionOpened',
    inputs: [{ name: 'player', type: 'address', indexed: true }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SessionClosed',
    inputs: [
      { name: 'player', type: 'address', indexed: true },
      { name: 'returnedAmount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SessionExpired',
    inputs: [
      { name: 'player', type: 'address', indexed: true },
      { name: 'returnedAmount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetPlaced',
    inputs: [
      { name: 'player', type: 'address', indexed: true },
      { name: 'betType', type: 'uint8', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetRemoved',
    inputs: [
      { name: 'player', type: 'address', indexed: true },
      { name: 'betType', type: 'uint8', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RollRequested',
    inputs: [
      { name: 'player', type: 'address', indexed: true },
      { name: 'requestId', type: 'uint256', indexed: true },
      { name: 'reservedAmount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RollResolved',
    inputs: [
      { name: 'player', type: 'address', indexed: true },
      { name: 'requestId', type: 'uint256', indexed: true },
      { name: 'die1', type: 'uint8', indexed: false },
      { name: 'die2', type: 'uint8', indexed: false },
      { name: 'payout', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BoxWorkingSet',
    inputs: [
      { name: 'player', type: 'address', indexed: true },
      { name: 'betType', type: 'uint8', indexed: true },
      { name: 'working', type: 'bool', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TurnExecuted',
    inputs: [
      { name: 'player', type: 'address', indexed: true },
      { name: 'actionCount', type: 'uint256', indexed: false },
      { name: 'rolled', type: 'bool', indexed: false },
      { name: 'requestId', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
] as const;
